spring:
  application:
    name: bo_tally
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:simple_accounting}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://124.220.63.130:3351/simple_accounting?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: tLo1d5mR5nDURjSs
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:fun/acowbo/simpleaccounting/db/migration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: prod
server:
  port: ${SERVER_PORT:17002}
logging:
  config: classpath:log4j2.xml
  level:
    fun:
      todoitbo:
        botally:
          mapper: debug
    com:
      baomidou:
        mybatisplus:
          extension:
            plugins:
              pagination:
                optimize:
                  JsqlParserCountOptimize: debug
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
